token swap prototype
pantheonxproject/xpn pull request #1
Opened 2020-07-22 02:31 UTC by bclabssong

2020-07-22 02:51 UTC, pantheonxofficial requested changes

2020-07-22 02:51 UTC, pantheonxofficial commented on contracts/YPN.sol
> +    uint256 private _totalSupply = 800000000 * 10 ** decimals;
@bclabssong  _totalSupply = 770000000 * 10 ** decimals;

2020-07-22 02:51 UTC, pantheonxofficial commented on truffle-config.js
> +     host: "192.168.1.15",     // Localhost (default: none)
@bclabssong  아이피를 바꾼 이유는?

2020-07-22 02:51 UTC, pantheonxofficial commented on package-lock.json
> +{
@bclabssong  lock 파일을 푸시한 이유는?

2020-07-22 02:51 UTC, pantheonxofficial commented on truffle-config.js
> +     port: 7545,            // Standard Ethereum port (default: none)
@bclabssong 환경적인 부분은 모든 사람이 영향을 받을 수 있는 부분임으로 임의의 변경시 고려가 필요함

2020-07-22 02:51 UTC, pantheonxofficial commented on contracts/Swap.sol
> +pragma solidity ^0.5.0;
@bclabssong 버전을 5.0으로 한 이유는?

2020-07-22 02:51 UTC, pantheonxofficial commented on contracts/Swap.sol
> +contract XPN is ERC20 {
@bclabssong 이미 컨트렉트가 배포되어 있는데, 이 부분을 소스를 삽입해야 하는 이유는? 배포된 컨트렉트를 실행 시킬 수 있을 것 같은데? 코드를 최적화 할 수 있는 방법을 찾아주길 바람

2020-07-22 05:12 UTC, bclabssong commented on contracts/YPN.sol
> +    uint256 private _totalSupply = 800000000 * 10 ** decimals;
반영하겠습니다.

2020-07-22 05:14 UTC, bclabssong commented on truffle-config.js
> +     host: "192.168.1.15",     // Localhost (default: none)
이게 제가 가나슈를 윈도우에서, 배포를 wsl에서 했는데, 내부IP가 각각 할당되는줄 알고 바꿔놓았습니다. 아이피 확인 해보니까 같은 내부 아이피 사용하네요.. 수정하겠습니다.

2020-07-27 02:39 UTC, pantheonxofficial requested changes

2020-07-27 02:39 UTC, pantheonxofficial commented on contracts/Swap.sol
> +pragma solidity ^0.5.0;
@bclabssong 0.6.x 와 0.5.x 와 기능 차이 검토 할 것

https://solidity.readthedocs.io/en/v0.6.12/050-breaking-changes.html

2020-07-27 02:39 UTC, pantheonxofficial commented on contracts/Whitelist.sol
> +pragma solidity ^0.6.0;
@bclabssong 최신이 0.6.12 인데 0.6.0 을 선택한 이유는?

2020-07-27 02:39 UTC, pantheonxofficial commented on contracts/Swap.sol
> +    // function setNewToken(YPN ypnTokenAddress) external {
@bclabssong 주석처리된 코드가 삽입된 이유는?
클린 코드 하세요

2020-07-27 02:39 UTC, pantheonxofficial commented on contracts/Whitelist.sol
> +    /**
@bclabssong 

https://solidity.readthedocs.io/en/v0.6.0/style-guide.html

스타일 가이드를 참조 하여, 클린 코드를 합시다.

2020-07-27 02:39 UTC, pantheonxofficial commented on package.json
> +    "solc": "^0.5.0"
@bclabssong package 추가 관련하여, solidity 버전 명시에 문제가 없는지 다시 한번 혹인 바람
https://www.npmjs.com/package/solc

2020-07-27 02:43 UTC, bclabssong commented on contracts/Whitelist.sol
> +pragma solidity ^0.6.0;
open-zeppelin에서 스테이블로 사용 하는 솔리디티 0.6.0 버전이라 해당 버전 으로 사용 했습니다.

2020-07-27 02:43 UTC, bclabssong commented on contracts/Swap.sol
> +    // function setNewToken(YPN ypnTokenAddress) external {
넵 알겠습니다.

2020-07-27 02:43 UTC, bclabssong commented on contracts/Whitelist.sol
> +    /**
넵 확인하겠습니다.

2020-07-27 02:44 UTC, bclabssong commented on package.json
> +    "solc": "^0.5.0"
넵 확인하겠습니다.

2020-07-27 04:37 UTC, pantheonxofficial commented on contracts/YPN.sol
> +    uint256 private _totalSupply = 800000000 * 10 ** decimals;
@bclabssong remind

2020-07-27 04:37 UTC, pantheonxofficial commented on truffle-config.js
> +     host: "192.168.1.15",     // Localhost (default: none)
@bclabssong remind

2020-07-27 04:37 UTC, pantheonxofficial commented on truffle-config.js
> +     port: 7545,            // Standard Ethereum port (default: none)
@bclabssong remind

2020-07-27 04:40 UTC, pantheonxofficial commented on contracts/Whitelist.sol
> +pragma solidity ^0.6.0;
@bclabssong https://github.com/ethereum/solidity/releases 변경 사항이나 문제 되는 사항이 있을 지 없을지 검토하고 다시 버전 선정을 하는 건 어떤지 체크 부탁 드려요.

2020-07-28 05:47 UTC, pantheonxofficial requested changes

2020-07-28 05:47 UTC, pantheonxofficial commented on contracts/Swap.sol
> +    function balanceOf(address owner) external view returns (uint256 balance);
@bclabssong  return type 구문 체크

2020-07-28 05:54 UTC, pantheonxofficial requested changes

2020-07-28 05:54 UTC, pantheonxofficial commented on migrations/2_Token_migration.js
> +const XPN = artifacts.require("./XPN.sol");
```javascript
const Migrations = artifacts.require("Migrations");
```

이 부분과 문법적으로 다르게 작성한 이유는?!

2020-07-28 05:54 UTC, pantheonxofficial commented on migrations/1_initial_migration.js
> +const Migrations = artifacts.require("Migrations");
```javascript
const XPN = artifacts.require("./XPN.sol");
```

2020-07-28 06:08 UTC, bclabssong commented on migrations/2_Token_migration.js
> +const XPN = artifacts.require("./XPN.sol");
solidity 0.6.12 버전을 사용하기 위해서 기존 마이그레이션 컨트랙트 변경이 필요했고 새로 truffle init 을 했습니다.
XPN 컨트랙트 마이그레이션 파일도 새 문법으로 변경할 계획이고 새로 생성한 컨트랙트 마이그레이션 작성시 신문법을 사용한 마이그레이션 파일을 만들 계획입니다.

2020-07-28 06:16 UTC, bclabssong commented on migrations/1_initial_migration.js
> +const Migrations = artifacts.require("Migrations");
컨트랙트 마이그레이션 파일에 트러플 새 문법 적용할 계획입니다.

2020-07-28 06:57 UTC, bclabssong commented on contracts/Swap.sol
> +    function balanceOf(address owner) external view returns (uint256 balance);
체크했습니다. 불필요하게 리턴변수명이 사용되었습니다. 해당 내용 수정하겠습니다.

2020-07-28 09:47 UTC, bclabssong commented
넵 알겠습니다.

2020-07-28 09:47 UTC, bclabssong commented
> @bclabssong xpn을 지우면, 테스트는 알아서 해야 하나요? 테스트 네트워크에서 실행 할 때, 최대한 간단히 실행할 수 있는 방법을 고려해서 설정하는 것을 목표로 하면 좋겠습니다.

넵 알겠습니다.

2020-07-28 09:51 UTC, bclabssong commented
> @bclabssong sh?

수정하였습니다..

2020-07-30 09:03 UTC, TaeGuNi requested changes

2020-07-30 09:03 UTC, TaeGuNi commented on test/Whitelist.js
> +  it("화이트리스트 컨트랙트 배포 여부 확인", async () => {
@bclabssong 글로벌 프로젝트라는 점을 생각하면, 가급적 한글이 포함된 코딩 보다는 영어 기반으로 하는 것이 좋아 보이네요.

2020-07-30 09:07 UTC, bclabssong commented on test/Whitelist.js
> +  it("화이트리스트 컨트랙트 배포 여부 확인", async () => {
넵. 반영하겠습니다.

2020-08-03 14:44 UTC, bclabssong reviewed
토큰 스왑 테스트코드를 제외한 나머지 테스트 코드는 정상 작동 합니다.

2020-08-03 14:44 UTC, bclabssong commented on test/contracts.js
> +  // });
토큰을 실제로 스왑하는 테스트 코드인데 트러플 테스트 환경에서는 정상적으로 테스팅 되지 않습니다.
리믹스로 트랜잭션을 보낼 시 정상 작동 합니다.

에러코드
Error: Returned error: VM Exception while processing transaction: revert
      at Context.it (test/contracts.js:75:24)
      at process._tickCallback (internal/process/next_tick.js:68:7)

2020-08-04 03:40 UTC, closed without merging